import Mathlib.Data.Real.Basic
import Mathlib.Tactic.NormNum

inductive TrafficLight where
  | red
  | yellow
  | green

def shouldStop : TrafficLight -> Bool
  | .red => true
  | .yellow => true
  | .green => false


inductive Shape where
  | circle (radius: Float)
  | rectangle (width: Float) (height: Float)

#check Shape.circle

def area : Shape → Float
  | .circle r       => 3.14159 * r * r
  | .rectangle w h  => w * h


inductive Nat' where
  | zero
  | succ (n : Nat')


def Nat'.add : Nat' → Nat' → Nat'
  | .zero,     m => m
  | .succ n,   m => .succ (add n m)

#eval Nat'.add Nat'.zero Nat'.zero


/- Dumb infinite type: -/

inductive Deep where
  | more (d: Deep)

/- The type itself is permissible. But it's empty. -/

theorem Deep.empty (d : Deep) : False := by
  induction d with
  | more d ih =>
      exact ih


/- List -/

/- The presence of (α : Type) here means that
  this is not a single type, but a type constructor.

  Its #check is List' : Type -> Type.
  (really, List' (α : Type) : Type)

  So this gets us to something like generics.
-/
inductive List' (α : Type) where
  | nil
  | cons (head: α) (tail: List' α)

#check List'

def List'.map :  (f: α -> β) -> List' α -> List' β
  | _, nil => nil
  | f, cons head tail => cons (f head) (map f tail)


/- It doesn't like this:

inductive StripeyList (α: Type) (β: Type) where
  | nil
  | cons (head: α) (tail: StripeyList β α)

The problem is that the parameters are supposed to stay fixed throughout the
entire inductive value, and we're swapping α and β here. The type changes as we
recurse.

-/

/- We can bump the universe and use indices -/

inductive StripeyList : Type → Type → Type 1 where
  | nil {α β : Type} :
      StripeyList α β

  | cons {α β : Type}
      (head : α)
      (tail : StripeyList β α) :
      StripeyList α β

/- Can also stay in the same universe and use a turn index: -/

inductive Turn where
  | a
  | b

inductive StripeyList' (α : Type) (β : Type) : Turn → Type where
  | nil {t : Turn} :
      StripeyList' α β t

  | consA (head : α) (tail : StripeyList' α β .b) :
      StripeyList' α β .a

  | consB (head : β) (tail : StripeyList' α β .a) :
      StripeyList' α β .b


/- Back up and take a simpler example that uses indices. (VERY simple) -/

inductive OnlyTrue : Bool → Type where
  | mk : OnlyTrue true

/- This is a family of two types, because it ranges over Bool. But only one has
a constuctor. -/

/- But this is valid: -/

#check OnlyTrue false

/- however, it does NOT mean there are any values of that type. -/

/- So OnlyTrue isn't well named. Bad example. -/

inductive Tiny : Nat → Type where
  | zero : Tiny 0
  | one  : Tiny 1


/- Only two here have a constructor, but this still works: -/
#check Tiny 37

/- Again, this just means that Tiny 37 is a valid type. But it is empty. -/

/- Whereas we do have a value of type Tiny 0: -/
#check Tiny.zero



/- Let's look at a version of vectors, with length encoded as an index. -/

inductive Vec (α : Type) : Nat → Type where
  | nil : Vec α 0
  | cons {n : Nat} (head : α) (tail : Vec α n) :
      Vec α (n + 1)

#check Vec.cons 10 Vec.nil

#check (Vec.cons 10 Vec.nil : Vec Nat 1)


/- there's a thing about reductions, lean docs mention it -/
#reduce (fun n => n + 1)
#reduce (fun n => 1 + n)

/- Indices are erased at runtime. But you can make weird structures where the
runtime data is also the type index. This is called the "singleton type"
pattern. -/

inductive Box (α : Type) : α → Type where
  | mk (x : α) : Box α x

#check Box Nat
-- Box Nat : Nat → Type

#check Box Nat 37
-- Box Nat 37 : Type

#check Box.mk 37
-- Box.mk 37 : Box Nat 37


/- Structure. -/

structure Person where
  firstName: String
  age: Nat

-- Make a structure:

def alice : Person :=
  {
    firstName := "Alice",
    age := 37
  }

#check alice.firstName
-- alice.name : String

#check alice.age
-- alice.age : Nat

-- autogenerated constructor:
#check Person.mk

-- record-update syntax:
def olderAlice : Person :=
  { alice with age := alice.age + 1 }

-- typeclasses.

class HasName (α : Type) where
  name : α → String

instance : HasName Person where
  name p := p.firstName



def greet (x : α) [HasName α] : String :=
  "Hello, " ++ HasName.name x


/- Make it more malleable with an explicitly-passable typeclass instance: -/

def greet' {α : Type} [h : HasName α] (x : α) : String :=
  "Hello, " ++ h.name x

/- You can have explicit, passable dispatch dictionaries as "objects" -/
def normalName : HasName Person :=
  ⟨fun p => p.firstName⟩

def sillyName : HasName Person :=
  ⟨fun _ => "BANANA"⟩

#eval greet' (h := normalName) alice
-- Hello, Alice

#eval greet' (h := sillyName) alice
-- Hello, BANANA


/- You can also have locally scoped ones, with letI, which registers the
instance for search: -/

def test : String :=
  letI : HasName Person :=
    {
      name := fun p => p.firstName.toUpper
    }

  greet' alice

#eval test

/- Local explicits also work as you'd expect -/

def test_2 : String :=
  let h : HasName Person :=
    {
      name := fun p => p.firstName.toUpper
    }

  greet' (h := h) alice

#eval test_2


/- Proving stuff -/

structure BoundedNat (bound_min : Nat) (bound_max : Nat) where
  value  : Nat
  min_le_val : bound_min ≤ value
  val_le_max : value ≤ bound_max

def the_bounded_nat : BoundedNat 10 100 where
  value := 37
  min_le_val := by decide
  val_le_max := by decide

theorem BoundedNat.min_le_max
    {min max : Nat}
    (x : BoundedNat min max) :
    min ≤ max := by
  exact Nat.le_trans x.min_le_val x.val_le_max

theorem BoundedNat.add_min_le_add_val
    {n₁ n₂ m₁ m₂ : Nat}
    (a : BoundedNat n₁ n₂)
    (b : BoundedNat m₁ m₂) :
    n₁ + m₁ ≤ a.value + b.value := by
  exact Nat.add_le_add a.min_le_val b.min_le_val

theorem BoundedNat.add_max_ge_add_val
    {n₁ n₂ m₁ m₂ : Nat}
    (a : BoundedNat n₁ n₂)
    (b : BoundedNat m₁ m₂) :
    n₂ + m₂ >= a.value + b.value := by
  exact Nat.add_le_add a.val_le_max b.val_le_max

/- get real -/

structure BoundedReal (bound_min : ℝ) (bound_max : ℝ) where
  value      : ℝ
  min_le_val : bound_min ≤ value
  val_le_max : value ≤ bound_max

theorem BoundedReal.min_le_max
    {min max : ℝ}
    (x : BoundedReal min max) :
    min ≤ max := by
  exact le_trans x.min_le_val x.val_le_max

theorem BoundedReal.add_min_le_add_val
    {n₁ n₂ m₁ m₂ : ℝ}
    (a : BoundedReal n₁ n₂)
    (b : BoundedReal m₁ m₂) :
    n₁ + m₁ ≤ a.value + b.value := by
  exact add_le_add a.min_le_val b.min_le_val

theorem BoundedReal.add_max_ge_add_val
    {n₁ n₂ m₁ m₂ : ℝ}
    (a : BoundedReal n₁ n₂)
    (b : BoundedReal m₁ m₂) :
    n₂ + m₂ ≥ a.value + b.value := by
  exact add_le_add a.val_le_max b.val_le_max


/- Get abstract -/

structure Bounded (α : Type) [Preorder α]
    (bound_min bound_max : α) where
  value      : α
  min_le_val : bound_min ≤ value
  val_le_max : value ≤ bound_max

theorem Bounded.min_le_max
    [Preorder α]
    {min max : α}
    (x : Bounded α min max) :
    min ≤ max := by
  exact le_trans x.min_le_val x.val_le_max

theorem Bounded.add_min_le_add_val
    [AddCommMonoid α] [Preorder α] [IsOrderedAddMonoid α]
    {n₁ n₂ m₁ m₂ : α}
    (a : Bounded α n₁ n₂)
    (b : Bounded α m₁ m₂) :
    n₁ + m₁ ≤ a.value + b.value := by
  exact add_le_add a.min_le_val b.min_le_val

theorem Bounded.add_max_ge_add_val
    [AddCommMonoid α] [Preorder α] [IsOrderedAddMonoid α]
    {n₁ n₂ m₁ m₂ : α}
    (a : Bounded α n₁ n₂)
    (b : Bounded α m₁ m₂) :
    n₂ + m₂ ≥ a.value + b.value := by
  exact add_le_add a.val_le_max b.val_le_max


/- Subtypes -/

#check Subtype

-- def SmallNat :=
--   {n : Nat // n ≤ 100}

/- the def form basically works, but abbrev is better for coercions and
typeclass synthesis and such, and is better for defining subtypes -/

abbrev SmallNat := {n : Nat // n ≤ 100}

def the_small_nat : SmallNat :=
  ⟨37, by decide⟩

#check the_small_nat.val
-- ↑the_small_nat : ℕ

#check the_small_nat.property
-- ↑the_small_nat ≤ 100

#print Subtype


def SmallNat.add
    (x y : SmallNat)
    (h : x.val + y.val ≤ 100) :
    SmallNat :=
  ⟨x.val + y.val, h⟩

/- Coercions -/

def SmallNat.add'
    (x y : SmallNat)
    (h : (↑x : Nat) + ↑y ≤ 100) :
    SmallNat :=
  ⟨↑x + ↑y, h⟩


/- Mutual recursion -/

mutual

inductive Tree (α : Type) where
  | node (value : α) (children : Forest α)

inductive Forest (α : Type) where
  | nil
  | cons (head : Tree α) (tail : Forest α)

end
