import LeanPlayground.Scratch.actual_scratch.scratch_02_inductive_types

/-!
# Typed trees from a signature

This is a concrete version of the categorical picture behind the
`Expr` exercises. A signature describes one layer of a tree; its well-founded
terms are the initial algebra of the resulting polynomial endofunctor.

Read the file in three passes: `Signature`/`Term` define the reusable theory;
`ExprShape` shows how the existing constructors fit it; the final section
derives evaluation preservation and subtree congruence from generic theorems.

Mathlib's `CategoryTheory.Endofunctor.Algebra` packages an algebra and its
morphisms in any category. Here the objects are indexed type families and the
morphisms are componentwise functions, so `Term.Algebra` and `Term.IsHom` spell
out those categorical definitions in the form used by the Lean programs.
-/

namespace PolynomialTrees

universe u v

/-- A constructor has an output sort, a shape, and typed child positions. -/
structure Signature (I : Type u) where
  Shape : I → Type v
  Pos : {i : I} → Shape i → Type v
  input : {i : I} → (s : Shape i) → Pos s → I

namespace Signature

/-- One layer of syntax with children supplied by the family `X`. -/
def Layer {I : Type u} (S : Signature.{u, v} I)
    (X : I → Type (max u v)) (i : I) : Type (max u v) :=
  Σ s : S.Shape i, (p : S.Pos s) → X (S.input s p)

/-- The action of a signature on a family of maps. -/
def map {I : Type u} (S : Signature.{u, v} I)
    {X Y : I → Type (max u v)} (f : ∀ i, X i → Y i) {i : I} :
    S.Layer X i → S.Layer Y i
  | ⟨s, children⟩ => ⟨s, fun p => f _ (children p)⟩

@[simp] theorem map_id {I : Type u} (S : Signature.{u, v} I)
    {X : I → Type (max u v)} {i : I} (x : S.Layer X i) :
    S.map (fun _ a => a) x = x := by
  rcases x with ⟨s, children⟩
  simp [map]

@[simp] theorem map_comp {I : Type u} (S : Signature.{u, v} I)
    {X Y Z : I → Type (max u v)} {i : I} (f : ∀ i, X i → Y i)
    (g : ∀ i, Y i → Z i) (x : S.Layer X i) :
    S.map g (S.map f x) = S.map (fun i a => g i (f i a)) x := by
  rcases x with ⟨s, children⟩
  rfl

end Signature

/-- The well-founded trees generated by a signature. -/
inductive Term {I : Type u} (S : Signature.{u, v} I) : I → Type (max u v) where
  | node {i : I} (s : S.Shape i)
      (children : (p : S.Pos s) → Term S (S.input s p)) : Term S i

namespace Term

/-- An algebra interprets one constructor after its children are interpreted. -/
abbrev Algebra {I : Type u} (S : Signature.{u, v} I)
    (X : I → Type (max u v)) := ∀ i, S.Layer X i → X i

/-- The unique interpretation determined by an algebra. -/
def fold {I : Type u} {S : Signature.{u, v} I}
    {X : I → Type (max u v)} (alg : Algebra S X) : ∀ {i}, Term S i → X i
  | _, .node s children =>
      alg _ ⟨s, fun p => fold alg (children p)⟩

/-- A map of algebras commutes with interpreting one layer. -/
def IsHom {I : Type u} {S : Signature.{u, v} I}
    {X Y : I → Type (max u v)}
    (source : Algebra S X) (target : Algebra S Y)
    (f : ∀ i, X i → Y i) : Prop :=
  ∀ i (layer : S.Layer X i),
    f i (source i layer) = target i (S.map f layer)

theorem fold_isHom {I : Type u} {S : Signature.{u, v} I}
    {X : I → Type (max u v)} (target : Algebra S X) :
    IsHom (fun _ layer => Term.node layer.1 layer.2) target
      (fun _ x => fold target x) := by
  intro i layer
  rcases layer with ⟨s, children⟩
  rfl

/-- Fold fusion: interpreting, then applying an algebra map, is one fold. -/
theorem fold_fusion {I : Type u} {S : Signature.{u, v} I}
    {X Y : I → Type (max u v)}
    (source : Algebra S X) (target : Algebra S Y)
    (f : ∀ i, X i → Y i) (hf : IsHom source target f)
    {i : I} (x : Term S i) :
    f i (fold source x) = fold target x := by
  induction x with
  | node s children ih =>
      change f _ (source _ ⟨s, fun p => fold source (children p)⟩) =
        target _ ⟨s, fun p => fold target (children p)⟩
      rw [hf]
      change target _ ⟨s, fun p => f _ (fold source (children p))⟩ =
        target _ ⟨s, fun p => fold target (children p)⟩
      have hchildren : (fun p => f _ (fold source (children p))) =
          (fun p => fold target (children p)) := funext ih
      rw [hchildren]

@[simp] theorem fold_constructor {I : Type u} {S : Signature.{u, v} I}
    {i : I} (x : Term S i) :
    fold (fun _ layer => Term.node layer.1 layer.2) x = x := by
  induction x with
  | node s children ih =>
      change Term.node s (fun p => fold (fun _ layer => Term.node layer.1 layer.2)
        (children p)) = Term.node s children
      congr 1
      funext p
      exact ih p

/-- Any algebra map out of terms is the fold: initiality in concrete form. -/
theorem hom_unique {I : Type u} {S : Signature.{u, v} I}
    {X : I → Type (max u v)}
    (target : Algebra S X) (f : ∀ i, Term S i → X i)
    (hf : IsHom (fun _ layer => Term.node layer.1 layer.2) target f)
    {i : I} (x : Term S i) : f i x = fold target x := by
  simpa only [fold_constructor] using
    fold_fusion (fun _ layer => Term.node layer.1 layer.2) target f hf x

/-!
An agreement certificate can stop at a subtree whose interpretations are
known equal, or descend through a common constructor. This is the structural
heart of the `firstDifferencePaths` theorem in the original scratch file.
Constructing a *minimal list of paths* additionally needs a finite ordering of
each constructor's positions and a way to decide whether heads match.
-/
inductive Agree {I : Type u} {S : Signature.{u, v} I}
    {X : I → Type (max u v)} (alg : Algebra S X) :
    {i : I} → Term S i → Term S i → Prop where
  | stop {i : I} {x y : Term S i}
      (h : fold alg x = fold alg y) : Agree alg x y
  | children {i : I} (s : S.Shape i)
      (left right : (p : S.Pos s) → Term S (S.input s p))
      (h : ∀ p, Agree alg (left p) (right p)) :
      Agree alg (.node s left) (.node s right)

/-- Agreement at the selected frontier implies agreement at the root. -/
theorem fold_eq_of_agree {I : Type u} {S : Signature.{u, v} I}
    {X : I → Type (max u v)} (alg : Algebra S X)
    {i : I} {x y : Term S i} (h : Agree alg x y) :
    fold alg x = fold alg y := by
  induction h with
  | stop heq => exact heq
  | children s left right _ ih =>
      change alg _ ⟨s, fun p => fold alg (left p)⟩ =
        alg _ ⟨s, fun p => fold alg (right p)⟩
      have hchildren : (fun p => fold alg (left p)) =
          (fun p => fold alg (right p)) := funext ih
      rw [hchildren]

end Term

open InductiveTypesScratch

/-! ## The signature of the existing typed expressions -/

inductive ExprShape : Ty → Type where
  | num (n : Nat) : ExprShape .nat
  | boolean (b : Bool) : ExprShape .bool
  | add : ExprShape .nat
  | twice : ExprShape .nat
  | isZero : ExprShape .bool
  | ite {t : Ty} : ExprShape t

inductive Two where
  | left
  | right

inductive Three where
  | condition
  | yes
  | no

abbrev ExprShape.pos : ExprShape t → Type
  | .num _ | .boolean _ => PEmpty
  | .add => Two
  | .twice | .isZero => PUnit
  | .ite => Three

abbrev ExprShape.input (s : ExprShape t) : s.pos → Ty :=
  match s with
  | .num _ | .boolean _ => fun p => p.elim
  | .add | .twice | .isZero => fun _ => .nat
  | .ite (t := t) => fun
      | .condition => .bool
      | .yes | .no => t

abbrev exprSignature : Signature Ty where
  Shape := ExprShape
  Pos := ExprShape.pos
  input := ExprShape.input

/-- The original constructors form an algebra for this signature. -/
def exprAlgebra : Term.Algebra exprSignature Expr :=
  fun _ ⟨s, children⟩ =>
    match s with
    | .num n => .num n
    | .boolean b => .boolean b
    | .add => .add (children .left) (children .right)
    | .twice => .twice (children .unit)
    | .isZero => .isZero (children .unit)
    | .ite => .ite (children .condition) (children .yes) (children .no)

/-- Interpret a signature tree as the original `Expr` inductive type. -/
def toExpr {t : Ty} : Term exprSignature t → Expr t :=
  Term.fold exprAlgebra

/-- Encode an original expression as a tree of the generic signature. -/
def ofExpr : {t : Ty} → Expr t → Term exprSignature t
  | _, .num n => .node (.num n) (fun p => p.elim)
  | _, .boolean b => .node (.boolean b) (fun p => p.elim)
  | _, .add left right => .node .add (fun
      | .left => ofExpr left
      | .right => ofExpr right)
  | _, .twice arg => .node .twice (fun _ => ofExpr arg)
  | _, .isZero arg => .node .isZero (fun _ => ofExpr arg)
  | _, .ite condition yes no => .node .ite (fun
      | .condition => ofExpr condition
      | .yes => ofExpr yes
      | .no => ofExpr no)

@[simp] theorem toExpr_ofExpr {t : Ty} (e : Expr t) :
    toExpr (ofExpr e) = e := by
  induction e with
  | num n => rfl
  | boolean b => rfl
  | add left right ihLeft ihRight =>
      change Expr.add (toExpr (ofExpr left)) (toExpr (ofExpr right)) = _
      rw [ihLeft, ihRight]
  | twice arg ih =>
      change Expr.twice (toExpr (ofExpr arg)) = _
      rw [ih]
  | isZero arg ih =>
      change Expr.isZero (toExpr (ofExpr arg)) = _
      rw [ih]
  | ite condition yes no ihCondition ihYes ihNo =>
      change Expr.ite (toExpr (ofExpr condition)) (toExpr (ofExpr yes))
        (toExpr (ofExpr no)) = _
      rw [ihCondition, ihYes, ihNo]

/-! ## Interpretation and a syntax pass as algebra maps -/

def evalAlgebra : Term.Algebra exprSignature Ty.denote :=
  fun _ ⟨s, children⟩ =>
    match s with
    | .num n => n
    | .boolean b => b
    | .add => children .left + children .right
    | .twice => children .unit + children .unit
    | .isZero => children .unit == 0
    | .ite => if children .condition then children .yes else children .no

theorem eval_isHom :
    Term.IsHom exprAlgebra evalAlgebra (fun _ e => Expr.eval e) := by
  intro i layer
  rcases layer with ⟨s, children⟩
  cases s <;> rfl

theorem eval_via_fold {t : Ty} (e : Expr t) :
    Term.fold evalAlgebra (ofExpr e) = e.eval := by
  calc
    Term.fold evalAlgebra (ofExpr e) = (toExpr (ofExpr e)).eval :=
      (Term.fold_fusion exprAlgebra evalAlgebra
        (fun _ e => Expr.eval e) eval_isHom (ofExpr e)).symm
    _ = e.eval := by rw [toExpr_ofExpr]

/-- A syntax algebra that replaces `twice` by `add`. -/
def desugarAlgebra : Term.Algebra exprSignature Expr :=
  fun _ ⟨s, children⟩ =>
    match s with
    | .num n => .num n
    | .boolean b => .boolean b
    | .add => .add (children .left) (children .right)
    | .twice => .add (children .unit) (children .unit)
    | .isZero => .isZero (children .unit)
    | .ite => .ite (children .condition) (children .yes) (children .no)

theorem desugar_isHom :
    Term.IsHom exprAlgebra desugarAlgebra (fun _ e => Expr.desugar e) := by
  intro i layer
  rcases layer with ⟨s, children⟩
  cases s <;> rfl

theorem desugar_via_fold {t : Ty} (e : Expr t) :
    Term.fold desugarAlgebra (ofExpr e) = Expr.desugar e := by
  calc
    Term.fold desugarAlgebra (ofExpr e) = Expr.desugar (toExpr (ofExpr e)) :=
      (Term.fold_fusion exprAlgebra desugarAlgebra
        (fun _ e => Expr.desugar e) desugar_isHom (ofExpr e)).symm
    _ = Expr.desugar e := by rw [toExpr_ofExpr]

/-- This one local check is all fusion needs for semantic preservation. -/
theorem eval_desugar_isHom :
    Term.IsHom desugarAlgebra evalAlgebra (fun _ e => Expr.eval e) := by
  intro i layer
  rcases layer with ⟨s, children⟩
  cases s <;> rfl

/-- The old six-case theorem is now an instance of generic fold fusion. -/
theorem eval_desugar_from_fusion {t : Ty} (e : Expr t) :
    (Expr.desugar e).eval = e.eval := by
  calc
    (Expr.desugar e).eval =
        Expr.eval (Term.fold desugarAlgebra (ofExpr e)) := by
          rw [desugar_via_fold]
    _ = Term.fold evalAlgebra (ofExpr e) :=
      Term.fold_fusion desugarAlgebra evalAlgebra
        (fun _ e => Expr.eval e) eval_desugar_isHom (ofExpr e)
    _ = e.eval := eval_via_fold e

/-- Transport the generic frontier theorem back to the existing syntax. -/
theorem expr_eval_eq_of_agree {t : Ty} (x y : Expr t)
    (h : Term.Agree evalAlgebra (ofExpr x) (ofExpr y)) :
    x.eval = y.eval := by
  rw [← eval_via_fold x, ← eval_via_fold y]
  exact Term.fold_eq_of_agree evalAlgebra h

-- Two different subtrees have the same value. The outer `ite` needs no
-- constructor-specific evaluation proof.
example (n : Nat) :
    (Expr.ite (.isZero (.num 0)) (.twice (.num n)) (.num 0)).eval =
      (Expr.ite (.boolean true) (.add (.num n) (.num n)) (.num 0)).eval := by
  apply expr_eval_eq_of_agree
  apply Term.Agree.children
  intro p
  cases p <;> apply Term.Agree.stop <;> rfl

end PolynomialTrees
