import LeanPlayground.Scratch.actual_scratch.polynomial_trees
import Mathlib.CategoryTheory.Endofunctor.Algebra

/-!
# The categorical version of polynomial trees

`polynomial_trees.lean` defines algebras and algebra maps component by
component. This file makes `Signature.Layer` an actual endofunctor and puts
those algebras in mathlib's `CategoryTheory.Endofunctor.Algebra` category.

## From a spec to concrete trees

A `Signature I` is a *specification of constructors*, not a collection of
trees. For each output sort `i`, it names the possible constructor shapes;
each shape has child positions, and each position specifies its child's sort.
`S.Layer X i` is one such constructor with its child slots filled by values
from a family `X`. Recursively filling those slots with more nodes gives the
concrete tree family `Term S i`. The structure map of `initialAlgebra S`
turns a layer of already built children into a new tree by calling `Term.node`.

For the running example, `exprSignature` describes the constructors of the
existing `Expr` type. `Term exprSignature` is the generic tree representation
of that spec; `ofExpr` encodes an existing `Expr` as such a tree, and
`toExpr_ofExpr` proves that interpreting the encoding with the original
constructors returns the starting expression. An algebra with some other
carrier supplies a meaning for each constructor, and its unique fold assigns
that meaning to every generated tree. `exprEvalAlgebra` chooses `Ty.denote`
as the carrier, so its fold computes expression values.

The main result is `isInitial`: for every signature `S`, its term algebra
`initialAlgebra S` is an initial object of that category. `foldHom` constructs
the arrow to any algebra, and `hom_eq_foldHom` proves it is the only arrow.
The declarations after `isInitial` show consequences and a concrete `Expr`
example; `eval_is_initial_arrow` is an example, not the initiality result.
-/

namespace PolynomialTrees.Category

open CategoryTheory

universe u v

/-- An object of the category of `I`-indexed type families. A morphism is a
function at each index, defined by the `Category` instance below. One can
view these families as functors from the discrete category on `I` to `Type`. -/
structure Family (I : Type u) where
  obj : I → Type (max u v)

namespace Family

instance (I : Type u) : Category (Family.{u, v} I) where
  Hom X Y := ∀ i, X.obj i → Y.obj i
  id _ := fun _ x => x
  comp f g := fun i x => g i (f i x)
  id_comp := by intros; rfl
  comp_id := by intros; rfl
  assoc := by intros; rfl

@[ext] theorem hom_ext {I : Type u} {X Y : Family.{u, v} I}
    {f g : X ⟶ Y} (h : ∀ i x, f i x = g i x) : f = g := by
  funext i x
  exact h i x

end Family

/-- The endofunctor induced by `S`. At index `i`, an object `X` is sent to
`Σ s : S.Shape i, (p : S.Pos s) → X (S.input s p)`. Its action on morphisms
maps every child while keeping the constructor shape. -/
def polynomial {I : Type u} (S : Signature.{u, v} I) :
    Family.{u, v} I ⥤ Family.{u, v} I where
  obj X := ⟨S.Layer X.obj⟩
  map f := fun _ => S.map f
  map_id := by
    intro X
    funext i x
    exact S.map_id x
  map_comp := by
    intro X Y Z f g
    funext i x
    exact S.map_comp f g x

/-- Package a componentwise operation `S.Layer X.obj i → X.obj i` as the
structure morphism of a mathlib endofunctor algebra. -/
def asAlgebra {I : Type u} (S : Signature.{u, v} I)
    (X : Family.{u, v} I) (alg : Term.Algebra S X.obj) :
    Endofunctor.Algebra (polynomial S) where
  a := X
  str := alg

/-- The algebra carried by `Term S`. Its structure map assembles one layer
of child terms into a term with the chosen root constructor. -/
def initialAlgebra {I : Type u} (S : Signature.{u, v} I) :
    Endofunctor.Algebra (polynomial S) :=
  asAlgebra S ⟨Term S⟩ (fun _ layer => Term.node layer.1 layer.2)

/-- For any algebra `A`, fold each term using `A.str`. The `h` field checks
that these componentwise folds form an algebra morphism. -/
def foldHom {I : Type u} (S : Signature.{u, v} I)
    (A : Endofunctor.Algebra (polynomial S)) :
    initialAlgebra S ⟶ A where
  f := fun _ x => Term.fold (fun i layer => A.str i layer) x
  h := by
    funext i layer
    exact (Term.fold_isHom (fun i layer => A.str i layer) i layer).symm

/-- Any algebra morphism from the term algebra to `A` equals `foldHom S A`.
This is the uniqueness half of initiality. -/
theorem hom_eq_foldHom {I : Type u} (S : Signature.{u, v} I)
    (A : Endofunctor.Algebra (polynomial S))
    (f : initialAlgebra S ⟶ A) : f = foldHom S A := by
  apply Endofunctor.Algebra.ext
  funext i x
  apply Term.hom_unique (fun i layer => A.str i layer) (fun i x => f.f i x)
  intro j layer
  have h := congrFun (congrFun f.h j) layer
  exact h.symm

/-- The initiality theorem: `Term S`, with `node` as its structure map, is
initial among algebras of the polynomial endofunctor generated by `S`. -/
def isInitial {I : Type u} (S : Signature.{u, v} I) :
    Limits.IsInitial (initialAlgebra S) :=
  Limits.IsInitial.ofUniqueHom (foldHom S) (hom_eq_foldHom S)

/-- Lambek's lemma, supplied by mathlib: the constructor map
`S.Layer (Term S) i → Term S i` is an isomorphism at every index. -/
theorem constructor_isIso {I : Type u} (S : Signature.{u, v} I) :
    IsIso (initialAlgebra S).str :=
  Endofunctor.Algebra.Initial.str_isIso (isInitial S)

open InductiveTypesScratch

/-- Interpret each `Expr` constructor in `Ty.denote`, packaging
`evalAlgebra` as an object of the algebra category. -/
def exprEvalAlgebra : Endofunctor.Algebra (polynomial exprSignature) :=
  asAlgebra exprSignature ⟨Ty.denote⟩ evalAlgebra

/-- For an original expression `e`, the unique arrow from the term algebra
to `exprEvalAlgebra` computes `e.eval` on its encoding `ofExpr e`. This uses
initiality; it is not itself the initiality theorem. -/
theorem eval_is_initial_arrow {t : Ty} (e : Expr t) :
    ((isInitial exprSignature).to exprEvalAlgebra).f t (ofExpr e) = e.eval := by
  rw [hom_eq_foldHom exprSignature exprEvalAlgebra
    ((isInitial exprSignature).to exprEvalAlgebra)]
  exact eval_via_fold e

end PolynomialTrees.Category
